### ISSUE TITLE
Some property are not set

### ISSUE THREAD

**Issue by eskan** [PaperfireElements/paperfire-stripe#1]
Hello,
i give a try to your element and it doesn't work as expected. It seems you configure the checkout to early : in ready() instead of the checkout button event. I've seen you've commented it. So email, firebase-url aren't set yet if they use binding.
May you take a look to this ?
Thanks in advance :D

**Comment by ackushiw** [comment]
@eskan Thanks for bringing this to my attention. I've push a new version. There are now two ways to configure the stripe checkout. 

As properties that are checked before opening the checkout or passing the the config object in when calling the open method. Or even both, with the config passed in taking priority. Details in the README

**Comment by eskan** [comment]
@ackushiw thanks to look at this.
I don't think the way you've done is a Polymer way. We need to be able to use databinding.
I see that firebase _ref is also defined at ready() may it should use a computed property instead.
Let me take a look to this i've just begin to look at stripe and i need it ;D
Cheers

**Comment by ackushiw** [comment]
@eskan Are you looking at `v2.1.0`
```
// Firebase ref
 _ref: {
    type: Object,
    computed: '_createRef(firebaseUrl)'
 }
```

**Comment by eskan** [comment]
nope !! i've just seen it .. good catch .. let's use this.
Thanks again

**Comment by ackushiw** [comment]
No problem, thanks for your feedback!
